### ISSUE TITLE
error about install

### ISSUE THREAD

**Issue by aimerlove4456** [jinhseo/OD-WSCL#12]
i meet the same problem about install apex and the last step-setup。
gpu：3090
pytorch：1.7.1+cu110
i use the conmand 
git clone --branch 22.04-dev https://github.com/NVIDIA/apex.git
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
then
if i use pip install -v --no-cache-dir ./
i will meet problem in the last step

can someone tell me how to install successful？

python setup.py build develop
running build
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 361, in build_extensions
    self._check_abi()
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 696, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 265, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 225, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/user1/anaconda3/envs/OD-WSCL2/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

**Comment by cyberpunk2040** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
